# Nome do Workflow de CD (Continuous Deployment)
name: CD - Deploy to Kubernetes

on:
  workflow_run:
    # O 'name' aqui DEVE ser idêntico ao 'name:' no seu arquivo ci.yml
    workflows: ["CI - Build & Push Docker"]
    types: ["completed"]
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    # Só executa se o workflow de CI (workflow_run) foi um SUCESSO
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production # opcional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          echo "IMAGE=ensfla/grafeno" >> $GITHUB_OUTPUT
          echo "TAG_SHA=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "NAMESPACE=${{ secrets.K8S_NAMESPACE || 'default' }}" >> $GITHUB_OUTPUT

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          (kubectl get ns ${{ steps.vars.outputs.NAMESPACE }} || \
          kubectl create ns ${{ steps.vars.outputs.NAMESPACE }}) || true

      - name: Apply base manifests (Service, Prometheus, Grafana, Nginx)
        run: |
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/service.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/prometheus-deployment.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/grafana-deployment.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/nginx-deployment.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/nginx-service.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/prometheus-config.yaml || true
          
          # --- ESTA É A LINHA ADICIONADA ---
          # Garante que a configuração do Nginx (que nós corrigimos) seja aplicada
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/nginx-configmap.yaml || true
          # --- FIM DA ADIÇÃO ---

      - name: Apply app deployment (first time)
        run: |
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/deployment.yaml || true

      - name: Set image to new tag
        run: |
          kubectl set image deployment/grafeno grafeno=${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }} -n ${{ steps.vars.outputs.NAMESPACE }} || true

      - name: Wait rollout
        run: |
          kubectl rollout status deployment/grafeno -n ${{ steps.vars.outputs.NAMESPACE }} --timeout=120s || true

      - name: Show services (debug)
        run: |
          kubectl get svc -n ${{ steps.vars.outputs.NAMESPACE }} || true
          kubectl get pods -o wide -n ${{ steps.vars.outputs.NAMESPACE }} || true